#+BEGIN_EXPORT html
---
title: "Productivity curve and social network analysis in science megaproject management"
tags: []
category: papers
excerpt: '"...a dense decision-making group that is only tenuously connected to technical expert teams via hierarchy."'
---
#+END_EXPORT

* What is this post about?
- Notes from reading the 2021 paper
  + "Productivity curve and social network analysis in science megaproject management"
  + by Phillip M. Bentley
  + https://iopscience.iop.org/article/10.1088/2399-6528/ac314c
* Short take
- Bottom-up study of a scientific facility heavy in instrumentation, in terms of productivity and inefficiencies in management
-  
* What do they do?
* How do they do it?
* Why do they do it?
* Conclusions and open questions
* Misc notes
- Uniqueness bias :: the desire to implement bespoke solutions instead of using established and more standard ones.
  + Often leads to more expensive and less efficient implementations
  + Reminds me of Hamming's warning, in his 1995 lectures (The Art of doing Science and Engineering),  against using custom chips for computing
  + "It is immensely ego gratifying to have special purpose chips for your special job, but there are very high costs associated with them"
- Forced Distribution Rating System (FDRS) :: When grades are distributed but there are fixed quotas for each grade, that way enforcing a pre-determined distribution
* Notes for Phil
- Citation suggestions
  + Geoffrey West's Scale book
  + Per Bak's How Nature Works book
- The Matthew Principle (the rich get richer...)
  + https://en.wikipedia.org/wiki/Matthew_effect
- Gauss was perhaps more a mathematician than a physicist
  + https://en.wikipedia.org/wiki/Carl_Friedrich_Gauss

* Twitter/Quotes
- Anonymized case study: clearly ESS but no names are mentioned.
- Open-source versus secret mode: mention this, even cite directly 



Fresh case study from the category of science @megaprojects, illustrating dysfunctional behavior as a rational response to management:
"..secrecy was stated as an actively chosen strategy for half of the highest performing staff in research, to avoid the impact that interference had on their work...some moderately important work was shared to give the impression of proactive openness to those senior in the hierarchy."
#planning @essneutron

https://iopscience.iop.org/article/10.1088/2399-6528/ac314c


